# from django.urls import path
# from .views import menu_items
# from . import views
# from django.shortcuts import get_list_or_404
# from rest_framework.authtoken.views import obtain_auth_token
# urlpatterns = [
#     # path('menu-items/', views.menu_items), # From API throttling for class-based views
#     # path('menu-items/<int:id>/', views.single_item), # From API throttling for class-based views
#     path('secret/', views.secret),
#     path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
#     path('menu-items/',views.MenuItemsViewSet.as_view({'get':'list'})), # From API throttling for class-based views
#     path('menu-items/<int:pk>',views.MenuItemsViewSet.as_view({'get':'retrieve'})),    # From API throttling for class-based views
# ]

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import MenuItemsViewSet, secret
from rest_framework.authtoken.views import obtain_auth_token
from . import views

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'menu-items', MenuItemsViewSet, basename='menuitem')

# Define your app's urlpatterns list.
urlpatterns = [
    # This line includes all URLs that are automatically generated by the router for the MenuItemsViewSet.
    path('', include(router.urls)),
    
    # Your custom URLs.
    path('secret/', secret, name='secret'),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
    path('groups/manager/users', views.managers),
]

# Note: You don't need to manually define 'menu-items/' and 'menu-items/<int:pk>' anymore,
# as they are already included by the router.
