file = open("text.txt", "r")
print(file.read())
file.close()

file = open("text.txt", "w+")
file.write("Hello World")
print(file.read())

file.close()
file = open("text.txt", "r")
print(file.read())
file.close()
file = open("text.txt", "a+")
file.write("Hello World")
print(file.read())
file.close()
file = open("text.txt", "r+")
file.write("Hello World")
print(file.read())
file.close()
file = open("text.txt", "w+")
file.write("Hello World")
print(file.read())
# file.close()

